ExcludeMouseTracking as marker component to opt-out a camera from mouse tracking
JoJoJet/bevy-mouse-tracking pull request #19
Opened 2022-08-20 14:15 UTC by EmmettJayhart

This PR resolves #18 about incompatible cameras, and possibly other issues that may have come down the line by allowing the user to manually opt-out individual cameras.

ExcludeMouseTracking is a marker component for any camera the user wishes to opt-out of mouse tracking.

By having this marker, a camera will not be given a MousePos or a MousePosWorld, and will also be excluded from the query when update_pos_ortho runs.

If an entity that has a MainCamera component also has an ExcludeTracking component, it will panic with an appropriate error message.

This PR does not allow users to use custom projections and mouse tracking on the same camera, it only allows the app to both have cameras for mouse tracking, and separate cameras with custom projections.

2022-08-21 17:09 UTC, JoJoJet requested changes
Thank you for bringing this issue to my attention. Ideally I would like to provide some way of supporting custom projections, but this is a good short-term solution.

Once you resolve the issues, I'll merge and publish it ASAP.

2022-08-21 17:09 UTC, joseph-gio commented on src/mouse_pos.rs
> +type NeedWorldspaceTracking = (Without<MousePosWorld>, Without<ExcludeMouseTracking>);
These type aliases are nice, I always like self-documenting code

2022-08-21 17:09 UTC, JoJoJet commented on src/lib.rs
> +//!
Good note, but this should be in the docs for `ExcludeMouseTracking`, not the README.

2022-08-21 17:09 UTC, JoJoJet commented on src/mouse_pos.rs
> +            .expect("only orthographic cameras are supported -- consider adding an ExcludeTracking component");
```suggestion
            .expect("only orthographic cameras are supported -- consider adding an ExcludeMouseTracking component");
```

2022-08-21 17:09 UTC, JoJoJet commented on src/mouse_pos.rs
> +        panic!("excluded main camera -- consider removing the ExcludeTracking component from the main camera")
```suggestion
        panic!("excluded main camera -- consider removing the ExcludeMouseTracking component from the main camera")
```

2022-08-21 17:09 UTC, JoJoJet commented on src/mouse_pos.rs
> +/// Any camera with this component will not be given a [`MousePos`] or [`MousePosWorld`] component.
```suggestion
/// Marker component for cameras that should be excluded from mouse tracking.
/// Any entity with this component will be ignored by [`MousePosPlugin`].
```

2022-08-21 23:47 UTC, EmmettJayhart commented on src/mouse_pos.rs
> +type NeedWorldspaceTracking = (Without<MousePosWorld>, Without<ExcludeMouseTracking>);
Thanks, it arised from the need to please clippy, as well as trying to avoid some ugly rustfmt formatting.

2022-08-22 00:05 UTC, EmmettJayhart commented
I have applied the suggested changes as well as updated some of the documentation.

It looks like the failed test suite is due to cargo running tests on the documentation code.
If you're looking for a fix for this, it's just the doctest field in Cargo.toml under [lib]

2022-08-22 00:07 UTC, JoJoJet commented
Keeping the doctests up to date is very important, but I can fix up the last issues if you don't want to go back and forth with CI.

2022-08-22 00:12 UTC, EmmettJayhart commented
Looking at how you've done the other tests, I see where it's going wrong.

2022-08-22 00:35 UTC, EmmettJayhart commented
I've fixed up the doctests. This was my first time ever using them so it was a great learning experience!

2022-08-22 01:10 UTC, JoJoJet approved these changes
Looks good. Thanks for contributing!

2022-08-22 02:35 UTC, merged